### ISSUE TITLE
Using with git annex?

### ISSUE THREAD

**Issue by PlasmaShift** [jgoerzen/gitsync-nncp#1]
I have a couple of questions about thinking about these 2 together
 1) Is there any difference between this and "git annex sync" or is gitsync-nncp only a subset of git annex.
 2) Can I run these together or would it be possible to run these together?
 3) Would there be any benefit in using gitsync-nncp and git annex in tandem

On a side note thanks for explaining the rational of creating this tool and why you used other tools. From reading your blog posts it looks like you went from git annex to syncthing to this. Do you still use git annex or syncthing for anything, sounds like you are using this for org mode notes.

I am testing git annex by managing my audio-books and am wanting to use git to manage my org mode notes. Git annex could be useful for org mode notes if you wanted to link your notes to bigger videos and audio books. youtube-dl for offline access to your reference of your notes

**Comment by jgoerzen** [comment]
Hi,

gitsync-nncp is different than git annex.  I wouldn't necessarily call either a subset of the other; they tackle different kinds of problems.  gitsync-nncp is all about handling things within git; git-annex handles things outside of git with some glue.

It probably would be possible to run them together, but I haven't tried it.

I don't know if there would be benefit to doing so.  I suppose if you had an external method to distribute the annex files, maybe.

You are correct that I went away from git annex to syncthing.  Though the particular files I use with gitsync-nncp were never in syncthing, because I specifically wanted the git history, and syncing a .git directory is a recipe for trouble.  I specifically do use it for org-mode and org-roam notes.

Hope that helps a bit!

**Comment by ehmry** [comment]
I imagine this would be done with git-annex helper: https://git-annex.branchable.com/special_remotes/external/

**Comment by ehmry** [comment]
I've done an annex key backend before so I'll try to implement this.

**Comment by jgoerzen** [comment]
That would be fantastic!  Thanks!

**Comment by ehmry** [comment]
Huzzah! https://git.sr.ht/~ehmry/git-annex-remote-nncp

**Comment by jgoerzen** [comment]
Forgot to comment - I am going to add this to the documentation today.  I am migrating off of github and this will be reflected on the new project at https://salsa.debian.org/jgoerzen/gitsync-nncp
